version: '3.8'

services:
  # Сервис для PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Сервис для Spring Boot приложения
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loadShield
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

# Том для хранения данных PostgreSQL
volumes:
  postgres_data: